variables:
  IMAGE_NAME: registry.upshon.net/tws
  IMAGE_TAG: latest


stages:          
  - build
  - deploy

build-job:       
  stage: build
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry.upshon.net
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    
deploy-job:      
  stage: deploy  
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
