version: '3.4'
services:
  tws:
    image: tws
    build: ./
    container_name: tws
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "8888:8888"
    ulimits:
      nofile: 10000
    environment:
      USERNAME: ${IB_ACCOUNT}
      PASSWORD: ${IB_PASSWORD}
      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: tws
      TZ: America/Chicago
    interactive-flag: true
    TTY-flag: true
