version: '3.4'
services:
  tws:
    image: registry.upshon.net/tws
    container_name: tws
    restart: unless-stopped
    ports:
      - "6080:6080"
      - "8888:8888"
    ulimits:
      nofile: 10000
    environment:
      IB_USERNAME: ${IB_ACCOUNT}
      IB_PASSWORD: ${IB_PASSWORD}
      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: tws
      TZ: America/Chicago
    tty: true
    stdin_open: true
