#!/bin/bash
exec /usr/bin/chromium \
    --no-sandbox \
    --test-type \
    --disable-dev-shm-usage \
    --disable-gpu \
    --disable-software-rasterizer \
    --force-dark-mode \
    --enable-features=WebContentsForceDark \
    "$@"
